language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

git:
  depth: 1

dist: trusty
sudo: required

env:
  matrix:
    - CANDY_MODE=REGULAR
    - CANDY_MODE=COVERAGE

matrix:
  # Coverage only on Linux/gcc
  exclude:
  - os: osx
    env: CANDY_MODE=COVERAGE
  - os: linux
    compiler: clang
    env: CANDY_MODE=COVERAGE

  allow_failures:
  # Travis' clang on Linux is too old: doesn't support the required builtins
  - os: linux
    compiler: clang

before_script:
  - if [ `uname` = "Linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa ;
      sudo add-apt-repository -y ppa:josh-bialkowski/cmake ;
      sudo apt-get update ;
      sudo apt-get install -y --force-yes cmake zlib1g-dev ;
    fi
  - if [ "$CANDY_MODE" = "COVERAGE" ]; then
      gem install coveralls-lcov ;
      sudo apt-get install lcov ;
    fi

script:
  - mkdir -p ../build
  - cd ../build

  - if [ "$CANDY_MODE" = "REGULAR" ]; then
      cmake -DCMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR ;
    fi
  - if [ "$CANDY_MODE" = "COVERAGE" ]; then
      cmake -DCMAKE_BUILD_TYPE=Debug -DCANDY_ENABLE_COVERAGE=ON $TRAVIS_BUILD_DIR ;
    fi

  - cmake --build . --config Release -- -j2
  - ctest -V

after_success:
 - if [ "$CANDY_MODE" = "COVERAGE" ]; then
     cd $TRAVIS_BUILD_DIR/../build ;
     lcov --directory . --capture --output-file coverage.info ;
     lcov --remove coverage.info 'testsrc/*' '/usr/*' --output-file coverage.info ;
     lcov --list coverage.info ;
     cd $TRAVIS_BUILD_DIR ; 
     coveralls-lcov ../build/coverage.info ;
   fi
